/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as extension from "./extension";
export type { extension };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { Booster } from "./Booster";
export type { Cards } from "./Cards";
