/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tokenBundleSol from "./TokenBundle.sol";
export type { tokenBundleSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { TokenStore } from "./TokenStore";
