/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC165__factory } from "./IERC165__factory";
export { IERC2981__factory } from "./IERC2981__factory";
